version: '2'

services:
    sim-global:
        image: chalmersrevere/opendlv-sim-global-amd64:v0.0.5
        network_mode: "host"
        command: "/usr/bin/opendlv-sim-global --cid=111 --freq=10 --frame-id=0 --x=0.0 --y=-0.0 --yaw=0.0"

    sim-motor-kiwi:
        image: chalmersrevere/opendlv-sim-motor-kiwi-amd64:v0.0.4
        network_mode: "host"
        command: "/usr/bin/opendlv-sim-motor-kiwi --cid=111 --freq=100 --frame-id=0"

    sim-ultrasonic-srf08-front:
        image: chalmersrevere/opendlv-sim-ultrasonic-srf08-amd64:v0.0.4
        network_mode: "host"
        volumes:
          - ./simulation-map.txt:/opt/simulation-map.txt
        command: "/usr/bin/opendlv-sim-ultrasonic-srf08 --map-file=/opt/simulation-map.txt --x=0.2 --y=0.0 --yaw=0.0 --cid=111 --freq=10 --frame-id=0 --id=0"
    
    sim-ultrasonic-srf08-rear:
        image: chalmersrevere/opendlv-sim-ultrasonic-srf08-amd64:v0.0.4
        network_mode: "host"
        volumes:
          - ./simulation-map.txt:/opt/simulation-map.txt
        command: "/usr/bin/opendlv-sim-ultrasonic-srf08 --map-file=/opt/simulation-map.txt --x=0.2 --y=0.0 --yaw=3.14 --cid=111 --freq=10 --frame-id=0 --id=1"
    
    sim-adc-bbblue-left:
        image: chalmersrevere/opendlv-sim-adc-bbblue-amd64:v0.0.4
        network_mode: "host"
        volumes:
          - ./simulation-map.txt:/opt/simulation-map.txt
        command: "/usr/bin/opendlv-sim-adc-bbblue --map-file=/opt/simulation-map.txt --x=0.0 --y=0.1 --yaw=1.57 --cid=111 --freq=10 --frame-id=0 --id=0"
    
    sim-adc-bbblue-right:
        image: chalmersrevere/opendlv-sim-adc-bbblue-amd64:v0.0.4
        network_mode: "host"
        volumes:
          - ./simulation-map.txt:/opt/simulation-map.txt
        command: "/usr/bin/opendlv-sim-adc-bbblue --map-file=/opt/simulation-map.txt --x=0.0 --y=-0.1 --yaw=-1.57 --cid=111 --freq=10 --frame-id=0 --id=1"
    
    logic-test-kiwi:
        image: bajs/123
        network_mode: "host"
        volumes:
          - ./simulation-map.txt:/opt/simulation-map.txt
        command: "/usr/bin/opendlv-logic-test-kiwi --cid=111 --freq=10 --frame-id=0 --forward_speed=0.1 --turnspeed_angle=0.1 --turn_angle=0.4 --reverse_speed=0.1 --reverseturnspeed_angle=0.05 --reverseturn_angle=0.4 --src_x=0.0 --src_y=0.0 --goal_x=1.75 --goal_y=1.7"

    ui-default:
        image: chalmersrevere/opendlv-ui-default-amd64:v0.0.3
        network_mode: "host"
        volumes:
          - ./simulation-map.txt:/srv/http/simulation-map.txt
        command: "--cid=111"
